### ISSUE TITLE
Fejl på udviklingsserver med .mp4-fil i galleriet.

### ISSUE THREAD

**Issue by furt11** [TK-IT/web#59]
Jeg får denne fejl, når jeg loader en side med en .mp4 fil på min lokale udviklingsserver. Jeg kan ikke gennemskue fejlen selv. Jeg aner heller ikke, om det kan være et lokalt problem, eller om det også vil opstå på produktionsserveren, når den tid kommer. Måske en af jer, kan tyde hvad python prøver, at sige mig? 
/FURT

Dump fra terminal: 
```
[14/Jun/2016 12:30:56] "GET /galleri/2013/halloj-pa-badehotellet/2016-05-07-174306.mp4 HTTP/1.1" 200 32933
[14/Jun/2016 12:30:58] "GET /media/2013/halloj-pa-badehotellet/2016-05-07-173427.mp4 HTTP/1.1" 200 23355392
[14/Jun/2016 12:30:58] "GET /media/2013/halloj-pa-badehotellet/2016-05-07-174306.mp4 HTTP/1.1" 200 25100288
Traceback (most recent call last):
Traceback (most recent call last):
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 279, in write
    self._write(data)
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 279, in write
    self._write(data)
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 453, in _write
    self.stdout.write(data)
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 453, in _write
    self.stdout.write(data)
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\socket.py", line 593, in write
    return self._sock.send(b)
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\socket.py", line 593, in write
    return self._sock.send(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
[14/Jun/2016 12:30:58] "GET /media/2013/halloj-pa-badehotellet/2016-05-07-174306.mp4 HTTP/1.1" 500 59
----------------------------------------
[14/Jun/2016 12:30:58] "GET /media/2013/halloj-pa-badehotellet/2016-05-07-173427.mp4 HTTP/1.1" 500 59
Exception happened during processing of request from ('127.0.0.1', 50925)
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 50927)
Traceback (most recent call last):
Traceback (most recent call last):
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 279, in write
    self._write(data)
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 453, in _write
    self.stdout.write(data)
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\socket.py", line 593, in write
    return self._sock.send(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 279, in write
    self._write(data)
Traceback (most recent call last):
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 141, in run
    self.handle_error()
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 453, in _write
    self.stdout.write(data)
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\socket.py", line 593, in write
    return self._sock.send(b)
  File "C:\Users\Martin\tk-web\web\venv\lib\site-packages\django\core\servers\basehttp.py", line 95, in handle_error
    super(ServerHandler, self).handle_error()
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 368, in handle_error
    self.finish_response()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 141, in run
    self.handle_error()
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "C:\Users\Martin\tk-web\web\venv\lib\site-packages\django\core\servers\basehttp.py", line 95, in handle_error
    super(ServerHandler, self).handle_error()
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 368, in handle_error
    self.finish_response()
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
TypeError: 'NoneType' object is not subscriptable
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():

During handling of the above exception, another exception occurred:

  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
Traceback (most recent call last):
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
Traceback (most recent call last):
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Martin\tk-web\web\venv\lib\site-packages\django\core\servers\basehttp.py", line 102, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "C:\Users\Martin\tk-web\web\venv\lib\site-packages\django\core\servers\basehttp.py", line 102, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\socketserver.py", line 684, in __init__
    self.handle()
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\socketserver.py", line 684, in __init__
    self.handle()
  File "C:\Users\Martin\tk-web\web\venv\lib\site-packages\django\core\servers\basehttp.py", line 182, in handle
    handler.run(self.server.get_app())
  File "C:\Users\Martin\tk-web\web\venv\lib\site-packages\django\core\servers\basehttp.py", line 182, in handle
    handler.run(self.server.get_app())
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 144, in run
    self.close()
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\handlers.py", line 144, in run
    self.close()
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
  File "c:\users\martin\appdata\local\programs\python\python35-32\Lib\wsgiref\simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
```

**Comment by neic** [comment]
Kører du din udviklings server med WSGI?

**Comment by furt11** [comment]
Jeg starter den med `python manage.py runserver --settings=tkweb.settings.dev 0.0.0.0:8000` - og har ikke tænkt mere over hvad der kører
.

**Comment by neic** [comment]
Prøv at kører `pip install --upgrade -r requirements.txt` (i dit venv).

**Comment by neic** [comment]
Er det her stadig et problem?

**Comment by furt11** [comment]
Ja, det har ikke ændret noget. Jeg er ikke en haj til debugging, så kan
ikke gennemskue, hvad der skaber problemerne. Traceback på
udviklingsserveren er magen til den, jeg oprindeligt postede.

fre. 24. jun. 2016 kl. 22.48 skrev Mathias Dannesbo <
notifications@github.com>:

**Comment by Mortal** [comment]
Jeg vil tro det ikke er et problem med vores setup, men et problem i wsgiref. Der er et [ubesvaret StackOverflow-spørgsmål om samme fejl](http://stackoverflow.com/q/37232149/1570972), og for mig lyder tracebacken som om der sker en Connection reset som bliver til en exception der ikke bliver håndteret.

Hvis vi er heldige er det en fejl der kun opstår på Windows.

**Comment by neic** [comment]
Det ser ud til at det er et problem med dit setup, ikke koden. Jeg lukker, du må genåbne hvis du syntes.

**Comment by furt11** [comment]
Det er skam helt fint.
