### ISSUE TITLE
InlineBaseMediaAdmin bliver ikke vist

### ISSUE THREAD

**Issue by neic** [TK-IT/web#70]
`InlineBaseMediaAdmin` bliver ikke vist, hverken i et nyt album, et album der er gemt, eller et album der er gemt og har billeder.

Gem fejler på album med følgende.
```
Internal Server Error: /admin/gallery/album/5383/
Traceback (most recent call last):
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/contrib/admin/options.py", line 618, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/contrib/admin/options.py", line 1521, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/contrib/admin/options.py", line 1468, in changeform_view
    if all_valid(formsets) and form_validated:
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/forms/formsets.py", line 439, in all_valid
    if not formset.is_valid():
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/forms/formsets.py", line 304, in is_valid
    self.errors
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/forms/formsets.py", line 278, in errors
    self.full_clean()
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/forms/formsets.py", line 325, in full_clean
    for i in range(0, self.total_form_count()):
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/forms/formsets.py", line 115, in total_form_count
    return min(self.management_form.cleaned_data[TOTAL_FORM_COUNT], self.absolute_max)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/forms/formsets.py", line 97, in management_form
    code='missing_management_form',
django.core.exceptions.ValidationError: ['ManagementForm-data mangler eller er blevet manipuleret']
```

Det er ser kun ud til at være et problem på prodekanus. Det hjælper ikke at fjerne ændringerne i bffc822be8e683de99a2855d80950bb5ed491357.

**Comment by neic** [comment]
Problemet var permissions. `www-data` havde ikke skrive rettigheder og kunne derfor ikke lave thumbnails. Jeg havde kørt `import-gallery.py` som `tkammer`. 
```
PermissionError: [Errno 13] Permission denied: '/Pictures/tkammer/media/cache'
```

[Template logging er indført i Django 1.9](https://docs.djangoproject.com/en/1.9/topics/logging/#django-template)
