### ISSUE TITLE
Databasefejl ved parallel upload

### ISSUE THREAD

**Issue by neic** [TK-IT/web#72]
Jeg prøvede at uploade 146 filer på 70--150KB via web til prodekanus. 3 filer fejlede med internal server error. Loggen har tre instanser af:

```python
Internal Server Error: /galleri/upload/
Traceback (most recent call last):
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/MySQLdb/cursors.py", line 217, in execute
    res = self._query(query)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/MySQLdb/cursors.py", line 378, in _query
    rowcount = self._do_query(q)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/MySQLdb/cursors.py", line 341, in _do_query
    db.query(q)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/tkammer/tkweb/tkweb/apps/gallery/views.py", line 123, in upload
    instance.save()
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/MySQLdb/cursors.py", line 217, in execute
    res = self._query(query)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/MySQLdb/cursors.py", line 378, in _query
    rowcount = self._do_query(q)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/MySQLdb/cursors.py", line 341, in _do_query
    db.query(q)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')
```

Jeg kunne godt uploade de tre filer alene efterfølgende. (Alene som ikke som en del af de 146)

**Comment by neic** [comment]
Det er rimelig konsekvent at den fejler på ~5% når den får en masse filer på min 25Mbit/s forbindelse. Det er sikker værre på AUs net.

Jeg har ca. 6 samtidige uploads. Det er kort tid der bliver brugt på selve upload, det meste tid går med thumbnail generation, db osv.

Giver man JFU `limitConcurrentUploads: 3` ser det ikke ud til at være et problem. Er det en løsning eller skal vi løse det underliggene problem? @Mortal

**Comment by neic** [comment]
Jeg har tilføjet `limitConcurrentUploads: 3` og fjerner det her issue fra v1.0 beta milestonen.

**Comment by neic** [comment]
Jeg har lige fået fejlen med `limitConcurrentUploads: 3`. Vi bliver nok nød til at  have løst det her rigtigt inden vi går live

**Comment by neic** [comment]
[MySQL dokumentationen](http://dev.mysql.com/doc/refman/5.7/en/innodb-deadlocks-handling.html) er ret brugbar. 

Jeg har ikke mysql root passwordet så jeg kan ikke tjekke `SHOW ENGINE INNODB STATUS`. 

Hvis vi "bare skal prøve igen" som der står vil jeg havde forventet at Django ORM enten håndterede det selv eller gjorde det nemt at gøre det. Se også [det her stackoverflow svar](http://stackoverflow.com/a/34275180/646921) om en patch til Django ORM.

**Comment by Mortal** [comment]
Her er det relevante output. (Jeg har sendt dig root-password via email.)

```
------------------------
LATEST DETECTED DEADLOCK
------------------------
160910 23:39:43
*** (1) TRANSACTION:
TRANSACTION E3072F, ACTIVE 0 sec inserting
mysql tables in use 1, locked 1
LOCK WAIT 7 lock struct(s), heap size 1248, 4 row lock(s), undo log entries 1
MySQL thread id 136591, OS thread handle 0x7fa3d3958700, query id 34411292 localhost tkammer update
INSERT INTO `gallery_image` (`basemedia_ptr_id`, `file`) VALUES (84373, '2017/test/havdrupvej4-160813-dsc_0114.jpg')
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 0 page no 1416 n bits 320 index `PRIMARY` of table `tkweb`.`gallery_image` trx id E3072F lock_mode X insert intention waiting
*** (2) TRANSACTION:
TRANSACTION E30730, ACTIVE 0 sec inserting
mysql tables in use 1, locked 1
7 lock struct(s), heap size 1248, 4 row lock(s), undo log entries 1
MySQL thread id 136592, OS thread handle 0x7fa3d3801700, query id 34411293 localhost tkammer update
INSERT INTO `gallery_image` (`basemedia_ptr_id`, `file`) VALUES (84374, '2017/test/havdrupvej4-160808-dsc_0112.jpg')
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 0 page no 1416 n bits 320 index `PRIMARY` of table `tkweb`.`gallery_image` trx id E30730 lock_mode X
*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 0 page no 1416 n bits 320 index `PRIMARY` of table `tkweb`.`gallery_image` trx id E30730 lock_mode X insert intention waiting
*** WE ROLL BACK TRANSACTION (2)
```

Det ligner at "transaction (2)" ovenfor har en lås som den prøver at opnå igen. Det ligner en bug, men måske læser jeg outputtet forkert.

**Comment by Mortal** [comment]
Her er en SO-post der minder meget om vores InnoDB output: http://stackoverflow.com/questions/23615641/why-am-i-getting-deadlock-in-mysql

**Comment by Mortal** [comment]
I siden [14.5.1 InnoDB Locking](http://dev.mysql.com/doc/refman/5.6/en/innodb-locking.html#innodb-gap-locks) står der at gap locking bliver slået fra hvis man skifter [Transaction Isolation Levels](http://dev.mysql.com/doc/refman/5.6/en/innodb-transaction-isolation-levels.html) til `READ COMMITTED`, hvad end det så betyder. Jeg kan ikke helt regne ud om det er gap locking der også giver os problemer, men i så fald kan vi jo prøve at ændre TX isolation level.

Alternativt kan vi finde et passende sted at sætte Django til at genstarte transaktionen hvis den bliver dræbt. Monkey patching, som foreslået i den SO post du fandt, er vel en fin løsning.

**Comment by neic** [comment]
Som jeg læser outputtet: T1 har en IX lock og T2 en X lock og vil gerne have en IX lock.

**Comment by Mortal** [comment]
Som jeg forstår [intention locks](http://dev.mysql.com/doc/refman/5.6/en/innodb-locking.html#innodb-intention-locks) skal man have en IX lock før man kan tage en X lock.

**Comment by neic** [comment]
Enig. Men det ser sådan ud på:
```SQL
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 0 page no 1416 n bits 320 index `PRIMARY` of table `tkweb`.`gallery_image` trx id E30730 lock_mode X
*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 0 page no 1416 n bits 320 index `PRIMARY` of table `tkweb`.`gallery_image` trx id E30730 lock_mode X insert intention waiting
```

**Comment by Mortal** [comment]
Ja, det ser sådan ud, men [SO-svaret jeg linkede ovenfor](http://stackoverflow.com/a/23619671/1570972) mener at outputtet er upålideligt:

"So, the InnoDB engine status was just wrong. It failed to show that each of the transactions held the same lock. It failed to show that each lock was lock_mode IX, not X. It failed to show that each thread also had an insert intention lock waiting to be granted. Altogether, it was a pretty spectacular failure of the `SHOW ENGINE INNODB STATUS;`."

**Comment by neic** [comment]
Okay. Det ser dog ikke ud til det er en gap lock. [Se her under `INSERT`](http://dev.mysql.com/doc/refman/5.6/en/innodb-locks-set.html)

> `INSERT` sets an exclusive lock on the inserted row. This lock is an index-record lock, not a next-key lock (that is, there is no gap lock) and does not prevent other sessions from inserting into the gap before the inserted row. […]

Det passer også med `RECORD LOCKS` i outputtet.

**Comment by neic** [comment]
Ifølge [Django bug 216770](https://code.djangoproject.com/ticket/21670) kan man sætte `select_on_save = True` for at bruge pre-1.6 `save()` som en workaround.

**Comment by neic** [comment]
Med 7eb7068c6cc23c86fa70a2e72f888e2f186562d4 ser det ud til at virke. Jeg har testet med billedesæt der før gav mindst en fejl rimeligt konsekvent. Jeg kan også smide hundredevis af ~10Kb billeder efter den uden at få en fejl.
