### ISSUE TITLE
Fejl ved migrering af idm data

### ISSUE THREAD

**Issue by neic** [TK-IT/web#73]
En import af data fra den gamle database giver følgende fejl når man kører `migrate idm --fake-initial` på prodekanus.
Der er ingen fejl hvis man ikke har importeret dataene i databasen først. Det kunne tyde på at det er et problem med encoding. Se [det her stackoverflow svar](http://stackoverflow.com/a/33142362/646921).

```python
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 91, in __exit__
    self.execute(sql)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/MySQLdb/cursors.py", line 217, in execute
    res = self._query(query)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/MySQLdb/cursors.py", line 378, in _query
    rowcount = self._do_query(q)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/MySQLdb/cursors.py", line 341, in _do_query
    db.query(q)
  File "/home/tkammer/tkweb/venv/lib/python3.4/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1005, "Can't create table 'tkweb.#sql-5c1_2057c' (errno: 150)")
```

**Comment by neic** [comment]
Begge databaser har `character_set_server` sat til `latin1` og alle tabeller i begge databaser har collation `latin1_swedish_ci`.

Overstående fejl kommer fra [`0003_create_relations.py`](https://github.com/TK-IT/web/blob/master/tkweb/apps/idm/migrations/0003_create_relations.py) som med `manage.py sqlmigration idm 0003` giver følgende: 

```SQL
BEGIN;
CREATE TABLE `idm_gradgroupmembership` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `grad` integer NOT NULL, `group_id` integer NOT NULL);
CREATE TABLE `idm_title` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `grad` integer NULL, `orgtitel` varchar(10) NOT NULL, `inttitel` varchar(10) NULL, `profile_id` integer NOT NULL);
CREATE TABLE `tkfolk_groups` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `profile_id` integer NOT NULL, `group_id` integer NOT NULL, UNIQUE (`profile_id`, `group_id`));
ALTER TABLE `idm_gradgroupmembership` ADD COLUMN `profile_id` integer NOT NULL;
ALTER TABLE `idm_gradgroupmembership` ALTER COLUMN `profile_id` DROP DEFAULT;
ALTER TABLE `idm_gradgroupmembership` ADD CONSTRAINT `idm_gradgroupmembership_group_id_1813b4919bafbda9_fk_grupper_id` FOREIGN KEY (`group_id`) REFERENCES `grupper` (`id`);
ALTER TABLE `idm_title` ADD CONSTRAINT `idm_title_profile_id_2b75e9ccec72347d_fk_tkfolk_id` FOREIGN KEY (`profile_id`) REFERENCES `tkfolk` (`id`);
ALTER TABLE `tkfolk_groups` ADD CONSTRAINT `tkfolk_groups_profile_id_55693a17da11871b_fk_tkfolk_id` FOREIGN KEY (`profile_id`) REFERENCES `tkfolk` (`id`);
ALTER TABLE `tkfolk_groups` ADD CONSTRAINT `tkfolk_groups_group_id_642d6690438e4b35_fk_grupper_id` FOREIGN KEY (`group_id`) REFERENCES `grupper` (`id`);
CREATE INDEX `idm_gradgroupmembership_83a0eb3f` ON `idm_gradgroupmembership` (`profile_id`);
ALTER TABLE `idm_gradgroupmembership` ADD CONSTRAINT `idm_gradgroupmembership_profile_id_6275bdd14d4a5067_fk_tkfolk_id` FOREIGN KEY (`profile_id`) REFERENCES `tkfolk` (`id`);

COMMIT;
```

Tabelnavnet `tkweb.#sql-5c1_2057c` fremtreder ikke nogen steder. Navnet ser heller ikke ud til at være konstant. Et andet eksempel er `tkweb.#sql-5c1_20bbd`.

**Comment by neic** [comment]
Sammenligner man SQLen fra migration `0001` og fra dumpet ser man at der er forskel på bla. typerne. I følge [den her kommetar på stackexchange](http://stackoverflow.com/a/4063164/646921) er det et problem når man bruger feltet som foreign key. Se eks `id` og `gone` i `adresse` tabellen:

```SQL
# Migration 0001
CREATE TABLE `adresser` (
  `id` integer NOT NULL PRIMARY KEY,
  `gade` varchar(50) NOT NULL,
  # […]
  `gone` integer NOT NULL
);

# Dump
CREATE TABLE `adresser` (
  `id` int(11) NOT NULL,
  `gade` varchar(50) NOT NULL,
  # […]
  `gone` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
```

**Comment by Mortal** [comment]
Men `int` er et alias af `integer` og 11 er standard-bredden af feltet, så jeg tror de to `id`-kolonner er defineret på samme måde.

**Comment by Mortal** [comment]
Hvad hvis vi skifter default engine til MyISAM? Så sker der ingen foreign key constraint checks på MySQL-serveren, men dem enforcer Django alligevel selv...

**Comment by Mortal** [comment]
Jeg har s/MyISAM/InnoDB/ i databasedumpet, og nu kan jeg fint importere, fake initial til 0001 og køre resten af migrations. Jeg tror problemet er løst?
